package com.memoreel.service;

import com.memoreel.common.exception.ResourceNotFoundException;
import com.memoreel.common.exception.UnauthorizedException;
import com.memoreel.common.exception.ValidationException;
import com.memoreel.common.util.FileValidator;
import com.memoreel.media.dto.MediaDTO;
import com.memoreel.media.dto.MediaUploadResponse;
import com.memoreel.media.dto.ReorderMediaRequest;
import com.memoreel.media.entity.Media;
import com.memoreel.media.entity.MediaType;
import com.memoreel.media.repository.MediaRepository;
import com.memoreel.project.entity.Project;
import com.memoreel.project.entity.ProjectStatus;
import com.memoreel.project.repository.ProjectRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Media service
 * Handles media upload, reordering, and deletion
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class MediaService {
    
    private final MediaRepository mediaRepository;
    private final ProjectRepository projectRepository;
    private final S3Service s3Service;
    private final FileValidator fileValidator;
    
    /**
     * Upload media to project
     * 
     * @param userId the user ID
     * @param projectId the project ID
     * @param file the media file
     * @return media upload response
     * @throws ValidationException if file is invalid or project status doesn't allow upload
     */
    @Transactional
    public MediaUploadResponse uploadMedia(Long userId, Long projectId, MultipartFile file) {
        log.info("Uploading media for project ID: {} by user ID: {}", projectId, userId);
        
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found"));
        
        validateProjectOwnership(project, userId);
        
        // Only DRAFT projects can have media uploaded
        if (project.getStatus() != ProjectStatus.DRAFT) {
            throw new ValidationException("Media can only be uploaded to draft projects");
        }
        
        // Determine media type and validate
        MediaType mediaType = determineMediaType(file);
        if (mediaType == MediaType.IMAGE) {
            fileValidator.validateImage(file);
        } else {
            fileValidator.validateVideo(file);
        }
        
        // Get next order index
        int nextOrderIndex = mediaRepository.findMaxOrderIndexByProjectId(projectId)
                .map(max -> max + 1)
                .orElse(0);
        
        // Upload to S3
        String folder = mediaType == MediaType.IMAGE ? "images" : "videos";
        String url = s3Service.uploadFile(file, folder);
        
        // Generate thumbnail URL (for videos, this would be generated by video processing)
        String thumbnailUrl = mediaType == MediaType.IMAGE ? url : null;
        
        // Create media entity
        Media media = Media.builder()
                .project(project)
                .type(mediaType)
                .url(url)
                .thumbnailUrl(thumbnailUrl)
                .orderIndex(nextOrderIndex)
                .size(file.getSize())
                .filename(file.getOriginalFilename())
                .build();
        
        media = mediaRepository.save(media);
        
        log.info("Media uploaded successfully with ID: {}", media.getId());
        
        return MediaUploadResponse.builder()
                .id(media.getId())
                .projectId(project.getId())
                .type(media.getType())
                .url(media.getUrl())
                .thumbnailUrl(media.getThumbnailUrl())
                .orderIndex(media.getOrderIndex())
                .size(media.getSize())
                .filename(media.getFilename())
                .uploadedAt(media.getCreatedAt())
                .build();
    }
    
    /**
     * Get project media ordered by orderIndex
     * 
     * @param userId the user ID
     * @param projectId the project ID
     * @return list of media DTOs
     */
    @Transactional(readOnly = true)
    public List<MediaDTO> getProjectMedia(Long userId, Long projectId) {
        log.info("Fetching media for project ID: {} by user ID: {}", projectId, userId);
        
        Project project = projectRepository.findById(projectId)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found"));
        
        validateProjectOwnership(project, userId);
        
        List<Media> mediaList = mediaRepository.findByProjectIdOrderByOrderIndexAsc(projectId);
        
        return mediaList.stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }
    
    /**
     * Reorder media item
     * 
     * @param userId the user ID
     * @param mediaId the media ID
     * @param request reorder request
     * @return updated media DTO
     */
    @Transactional
    public MediaDTO reorderMedia(Long userId, Long mediaId, ReorderMediaRequest request) {
        log.info("Reordering media ID: {} to index: {}", mediaId, request.getNewOrderIndex());
        
        Media media = mediaRepository.findById(mediaId)
                .orElseThrow(() -> new ResourceNotFoundException("Media not found"));
        
        validateProjectOwnership(media.getProject(), userId);
        
        // Only DRAFT projects can have media reordered
        if (media.getProject().getStatus() != ProjectStatus.DRAFT) {
            throw new ValidationException("Media can only be reordered in draft projects");
        }
        
        int oldIndex = media.getOrderIndex();
        int newIndex = request.getNewOrderIndex();
        
        if (oldIndex == newIndex) {
            return convertToDTO(media);
        }
        
        // Get all media for the project
        List<Media> allMedia = mediaRepository.findByProjectIdOrderByOrderIndexAsc(media.getProject().getId());
        
        // Validate new index
        if (newIndex < 0 || newIndex >= allMedia.size()) {
            throw new ValidationException("Invalid order index");
        }
        
        // Reorder media items
        if (oldIndex < newIndex) {
            // Moving down: shift items up
            for (Media m : allMedia) {
                if (m.getOrderIndex() > oldIndex && m.getOrderIndex() <= newIndex) {
                    m.setOrderIndex(m.getOrderIndex() - 1);
                }
            }
        } else {
            // Moving up: shift items down
            for (Media m : allMedia) {
                if (m.getOrderIndex() >= newIndex && m.getOrderIndex() < oldIndex) {
                    m.setOrderIndex(m.getOrderIndex() + 1);
                }
            }
        }
        
        media.setOrderIndex(newIndex);
        mediaRepository.saveAll(allMedia);
        
        log.info("Media reordered successfully: {}", mediaId);
        
        return convertToDTO(media);
    }
    
    /**
     * Delete media
     * 
     * @param userId the user ID
     * @param mediaId the media ID
     */
    @Transactional
    public void deleteMedia(Long userId, Long mediaId) {
        log.info("Deleting media ID: {} by user ID: {}", mediaId, userId);
        
        Media media = mediaRepository.findById(mediaId)
                .orElseThrow(() -> new ResourceNotFoundException("Media not found"));
        
        validateProjectOwnership(media.getProject(), userId);
        
        // Only DRAFT projects can have media deleted
        if (media.getProject().getStatus() != ProjectStatus.DRAFT) {
            throw new ValidationException("Media can only be deleted from draft projects");
        }
        
        // Delete from S3
        s3Service.deleteFile(media.getUrl());
        if (media.getThumbnailUrl() != null && !media.getThumbnailUrl().equals(media.getUrl())) {
            s3Service.deleteFile(media.getThumbnailUrl());
        }
        
        // Delete from database
        mediaRepository.delete(media);
        
        // Reorder remaining media
        List<Media> remainingMedia = mediaRepository.findByProjectIdOrderByOrderIndexAsc(media.getProject().getId());
        for (int i = 0; i < remainingMedia.size(); i++) {
            remainingMedia.get(i).setOrderIndex(i);
        }
        mediaRepository.saveAll(remainingMedia);
        
        log.info("Media deleted successfully: {}", mediaId);
    }
    
    /**
     * Determine media type from file
     * 
     * @param file the file
     * @return media type
     */
    private MediaType determineMediaType(MultipartFile file) {
        String contentType = file.getContentType();
        if (contentType != null) {
            if (contentType.startsWith("image/")) {
                return MediaType.IMAGE;
            } else if (contentType.startsWith("video/")) {
                return MediaType.VIDEO;
            }
        }
        throw new ValidationException("Unsupported file type");
    }
    
    /**
     * Validate project ownership
     * 
     * @param project the project
     * @param userId the user ID
     */
    private void validateProjectOwnership(Project project, Long userId) {
        if (!project.getUser().getId().equals(userId)) {
            throw new UnauthorizedException("You don't have permission to access this project");
        }
    }
    
    /**
     * Convert Media entity to DTO
     * 
     * @param media the media entity
     * @return media DTO
     */
    private MediaDTO convertToDTO(Media media) {
        return MediaDTO.builder()
                .id(media.getId())
                .projectId(media.getProject().getId())
                .type(media.getType())
                .url(media.getUrl())
                .thumbnailUrl(media.getThumbnailUrl())
                .orderIndex(media.getOrderIndex())
                .size(media.getSize())
                .createdAt(media.getCreatedAt())
                .build();
    }
}

// Made with Bob
